apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: juphc-tc-pipeline-run-
spec:
  serviceAccountName: pipeline
  pipelineRef:
    name: juphc-tc-pipeline
  params:
    - name: repo-url
      value: "https://github.com/ubaidullahmiani/zntwk-tax_calculator.git"
    - name: branch
      value: "main"
    - name: app-name
      value: "tax-calculator"
    - name: build-image
      value: "us.icr.io/sn-labs-ubaidullahmi/tax-calculator"
  workspaces:
    - name: pipeline-workspace
      persistentVolumeClaim:
        claimName: pipelinerun-pvc
    - name: dockerconfig-ws
      secret:
        secretName: docker-reg-creds