---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cleanup
spec:
  workspaces:
    - name: source
  steps:
    - name: cleanup
      image: alpine:3.18
      workingDir: $(workspaces.source.path)
      script: |
        #!/bin/sh
        set -e
        echo "***** Cleaning workspace *****"
        rm -rf ./*
        rm -rf ./.git
        echo "***** Workspace cleaned *****"